AWSTemplateFormatVersion: "2010-09-09"
Description: Make Luna recognize things
Resources:
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/AmazonSNSFullAccess'
        - 'arn:aws:iam::aws:policy/AWSLambdaInvocation-DynamoDB'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  LunaPPMVision:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: ''
        S3Key: '.'
      Description: Make Luna recognize things
      MemorySize: 2048
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.9
      Handler: service.handler
      Timeout: 120